Merge contactsList to master
ArturKhachatryan13/Contacts pull request #2
Opened 2022-07-01 15:39 UTC by ArturKhachatryan13

2022-07-05 09:26 UTC, AnushavanGhulyan requested changes
Please make attention to folder and file names.

if you have a "Components" folder.
make folder names inside it without the "component" suffix

for example.
now you have  "src/Components/ContactsListComponents/ContactImage.js".
It's more clear to have "src/Components/List/index.js".

store Images or similar static assets. inside "src/assets" or just "assets" folder in root.

2022-07-05 09:26 UTC, AnushavanGhulyan commented on src/Screens/HomeScreen.js
> +      </View>
Please remove unnecessary Views

2022-07-05 09:26 UTC, AnushavanGhulyan commented on src/Components/ContactsListComponents/EveryContact.js
> +      </View>
Unnecessary View

2022-07-05 09:26 UTC, AnushavanGhulyan commented on src/Components/ContactsListComponents/ContactsList.js
> +    </View>
Unnecessary View

2022-07-05 09:26 UTC, AnushavanGhulyan commented on src/Components/ContactsListComponents/ContactsList.js
> +import React from 'react';
Please rename component folder from ContactsListComponent to ContactList.
and rename the file name from ContactList to index.js.

this makes the import statement more readable.

2022-07-05 09:26 UTC, AnushavanGhulyan commented on src/Components/ContactsListComponents/ContactImage.js
> +    </View>
Please make constant variables in "const",
Create small components out of ContactImage.
1, <Initials />, and pass name. write logic inside the component.
2, <Avatar /> and pass image prop.

2022-07-05 09:26 UTC, AnushavanGhulyan commented on src/Components/ContactsListComponents/ContactsList.js
> +  };
Please do destructuring.  contacts =>  ({ item. index }),
change contacts prop to contact and pass only Item.

2022-07-05 09:26 UTC, AnushavanGhulyan commented on src/Components/ContactsListComponents/ContactsList.js
> +    name: 'Aron Ashluxe',
Please change the name key. store name and surname separated

2022-07-06 17:37 UTC, griarman requested changes

2022-07-06 17:37 UTC, griarman commented on src/Components/List/ContactsList.js
> +    return element;
just write `
{
name: newName[randomindexforName],
...etc.
}
`

2022-07-06 17:37 UTC, griarman commented on src/Components/List/ContactsList.js
> +const name = [
please move all this constant data into constant directory, and move generateData, compare and changeDataStructure functions into utils

2022-07-06 17:37 UTC, griarman commented on src/Components/List/ContactsList.js
> +        keyExtractor={(item, index) => item + index}
in future don't use index as key

2022-07-06 17:37 UTC, griarman commented on src/Components/List/ContactsList.js
> +// new part
memorize this part

2022-07-06 17:37 UTC, griarman commented on src/Components/List/ContactsList.js
> +  return sectionListArray;
please use reduce instead of this

2022-07-06 17:37 UTC, griarman commented on src/Components/List/EveryContact.js
> +        <Text style={styles.name}>{title.name + ' ' + title.surname}</Text>
be sure that user have surname, cause in other hand it will render undefined

2022-07-06 17:37 UTC, griarman commented on src/Components/List/EveryContact.js
> +    borderBottomColor: '#D9DBE9',
please create COLORS file, and add all you colors there, and use that constant value

2022-07-06 17:37 UTC, griarman commented on src/Components/List/UserInitial.js
> +  const userInitials = contact.name[0] + contact.surname[0];
again user may not have surname and memorize this data

2022-07-06 17:37 UTC, griarman commented on src/Screens/HomeScreen.js
> +      </View>
i think this comment is still actual

2022-07-06 17:37 UTC, griarman commented on src/Navigation/index.js
> +        screenOptions={{ cardStyle: { backgroundColor: '#fff' } }}>
don't use screenOptions this way

2022-07-06 17:37 UTC, griarman commented on src/Components/List/ContactImage.js
> +import React from 'react';
let move this file into UI kit, and add image styles for small | medium | large types

2022-07-08 14:50 UTC, AnushavanGhulyan requested changes

2022-07-08 14:50 UTC, AnushavanGhulyan commented on src/Components/List/ContactsList.js
> +import SectionTitle from './SectionTitle';
This is small component, so bring it into this file

2022-07-08 14:50 UTC, AnushavanGhulyan commented on src/Screens/HomeScreen.js
> +  let flatData = getFavorateContacts(firstGanaretedData);
use const for constants variables

2022-07-08 14:50 UTC, AnushavanGhulyan commented on src/Screens/HomeScreen.js
> +    () => changeDataStructure(generetedData.sort(compare)),
sort copy of the array. not mutate the original object

2022-07-08 14:50 UTC, AnushavanGhulyan commented on src/ui-kit/Avatar/containerSize.js
> +});
remove repeated parts of styles.

2022-07-08 14:50 UTC, AnushavanGhulyan commented on src/ui-kit/Avatar/size.js
> +  },
same here.

2022-07-08 14:50 UTC, AnushavanGhulyan commented on utils/constants.js
> +const img = [
add also several image urls

2022-07-08 14:50 UTC, AnushavanGhulyan commented on utils/helperFunctions/сontactsListGenerator.js
> +  // return filterList;
remove commented code

2022-07-08 14:50 UTC, AnushavanGhulyan commented on utils/helperFunctions/сontactsListGenerator.js
> +  return filterList;
remove unnecessary variable

2022-07-08 14:50 UTC, AnushavanGhulyan commented on utils/helperFunctions/сontactsListGenerator.js
> +  if (a.name < b.name) return -1;
optimize checking

2022-07-08 14:50 UTC, AnushavanGhulyan commented on utils/helperFunctions/сontactsListGenerator.js
> +};
use reduce function

2022-07-11 17:04 UTC, griarman requested changes

2022-07-11 17:04 UTC, griarman commented on utils/colors.js
> +export default {
please add here other colors like white

2022-07-13 11:43 UTC, AnushavanGhulyan approved these changes

2022-07-13 11:58 UTC, griarman requested changes

2022-07-13 11:58 UTC, griarman commented on src/ui-kit/Avatar/index.js
> +    return `${name[0]}${surname[0] || ''}`;
please add ?. `surname[0]`

2022-07-13 12:22 UTC, merged